/**
 * 游戏配置项定义
 */

export interface ConfigOption {
    key: string
    label: string
    description?: string
    type: "number" | "boolean" | "string" | "select" | "resolution"
    defaultValue?: any
    options?: { label: string; value: string | number | number }[]
    section: string
    enabled?: number
}

export interface ConfigCategory {
    name: string
    label: string
    description?: string
    options: ConfigOption[]
}

/**
 * GameUserSettings.ini 配置项定义
 */
export const gameUserSettingsConfigCategories: ConfigCategory[] = [
    {
        name: "gameUserSettings",
        label: "游戏设置",
        description: "游戏图形质量预设",
        options: [
            {
                key: "ResolutionSize",
                label: "分辨率",
                description: "游戏窗口分辨率",
                type: "resolution",
                section: "/Script/Engine.GameUserSettings",
                defaultValue: { width: 1600, height: 900 },
            },
            // {
            //     key: "Language",
            //     label: "语言",
            //     description: "游戏语言设置",
            //     type: "select",
            //     section: "Internationalization",
            //     defaultValue: "en",
            //     options: [
            //         { label: "English", value: "en" },
            //         { label: "简体中文", value: "zh-CN" },
            //         { label: "繁體中文", value: "zh-TW" },
            //         { label: "日本語", value: "ja" },
            //         { label: "한국어", value: "ko" },
            //     ],
            // },
            {
                key: "sg.ResolutionQuality",
                label: "渲染分辨率",
                description: "渲染分辨率比例",
                type: "number",
                section: "ScalabilityGroups",
                defaultValue: 100,
            },
            {
                key: "sg.ViewDistanceQuality",
                label: "视距质量",
                description: "视距渲染质量",
                type: "select",
                section: "ScalabilityGroups",
                defaultValue: 4,
                options: [
                    { label: "极低", value: 0 },
                    { label: "低", value: 1 },
                    { label: "中", value: 2 },
                    { label: "高", value: 3 },
                    { label: "极高", value: 4 },
                ],
            },
            {
                key: "sg.AntiAliasingQuality",
                label: "抗锯齿质量",
                description: "抗锯齿渲染质量",
                type: "select",
                section: "ScalabilityGroups",
                defaultValue: 4,
                options: [
                    { label: "极低", value: 0 },
                    { label: "低", value: 1 },
                    { label: "中", value: 2 },
                    { label: "高", value: 3 },
                    { label: "极高", value: 4 },
                ],
            },
            {
                key: "sg.ShadowQuality",
                label: "阴影质量",
                description: "阴影渲染质量",
                type: "select",
                section: "ScalabilityGroups",
                defaultValue: 4,
                options: [
                    { label: "极低", value: 0 },
                    { label: "低", value: 1 },
                    { label: "中", value: 2 },
                    { label: "高", value: 3 },
                    { label: "极高", value: 4 },
                ],
            },
            {
                key: "sg.PostProcessQuality",
                label: "后处理质量",
                description: "后处理效果质量",
                type: "select",
                section: "ScalabilityGroups",
                defaultValue: 4,
                options: [
                    { label: "极低", value: 0 },
                    { label: "低", value: 1 },
                    { label: "中", value: 2 },
                    { label: "高", value: 3 },
                    { label: "极高", value: 4 },
                ],
            },
            {
                key: "sg.TextureQuality",
                label: "纹理质量",
                description: "纹理渲染质量",
                type: "select",
                section: "ScalabilityGroups",
                defaultValue: 4,
                options: [
                    { label: "极低", value: 0 },
                    { label: "低", value: 1 },
                    { label: "中", value: 2 },
                    { label: "高", value: 3 },
                    { label: "极高", value: 4 },
                ],
            },
            {
                key: "sg.EffectsQuality",
                label: "特效质量",
                description: "特效渲染质量",
                type: "select",
                section: "ScalabilityGroups",
                defaultValue: 4,
                options: [
                    { label: "极低", value: 0 },
                    { label: "低", value: 1 },
                    { label: "中", value: 2 },
                    { label: "高", value: 3 },
                    { label: "极高", value: 4 },
                ],
            },
            {
                key: "sg.FoliageQuality",
                label: "植被质量",
                description: "植被渲染质量",
                type: "select",
                section: "ScalabilityGroups",
                defaultValue: 4,
                options: [
                    { label: "极低", value: 0 },
                    { label: "低", value: 1 },
                    { label: "中", value: 2 },
                    { label: "高", value: 3 },
                    { label: "极高", value: 4 },
                ],
            },
            {
                key: "sg.ShadingQuality",
                label: "着色质量",
                description: "着色渲染质量",
                type: "select",
                section: "ScalabilityGroups",
                defaultValue: 4,
                options: [
                    { label: "极低", value: 0 },
                    { label: "低", value: 1 },
                    { label: "中", value: 2 },
                    { label: "高", value: 3 },
                    { label: "极高", value: 4 },
                ],
            },
            {
                key: "bUseVSync",
                label: "垂直同步",
                description: "启用/禁用垂直同步",
                type: "boolean",
                section: "/Script/Engine.GameUserSettings",
                defaultValue: false,
            },
            {
                key: "bUseDynamicResolution",
                label: "动态分辨率",
                description: "启用/禁用动态分辨率",
                type: "boolean",
                section: "/Script/Engine.GameUserSettings",
                defaultValue: false,
            },
            {
                key: "FullscreenMode",
                label: "全屏模式",
                description: "全屏显示模式",
                type: "select",
                section: "/Script/Engine.GameUserSettings",
                defaultValue: 2,
                options: [
                    { label: "全屏", value: 0 },
                    { label: "无边框窗口", value: 1 },
                    { label: "窗口化", value: 2 },
                ],
            },
            {
                key: "FrameRateLimit",
                label: "帧率限制",
                description: "最大帧率限制（0为无限制）",
                type: "number",
                section: "/Script/Engine.GameUserSettings",
                defaultValue: 60,
            },
            {
                key: "AudioQualityLevel",
                label: "音频质量",
                description: "音频质量级别",
                type: "select",
                section: "/Script/Engine.GameUserSettings",
                defaultValue: 0,
                options: [
                    { label: "低", value: 0 },
                    { label: "中", value: 1 },
                    { label: "高", value: 2 },
                ],
            },
        ],
    },
]

/**
 * Engine.ini 配置项定义
 */
export const engineConfigCategories: ConfigCategory[] = [
    {
        name: "systemSettings",
        label: "系统设置",
        description: "系统级渲染和性能设置",
        options: [
            {
                key: "r.PostProcessQuality",
                label: "后处理质量",
                description: "覆盖游戏内视觉效果质量（后处理）",
                type: "select",
                section: "SystemSettings",
                defaultValue: 0,
                options: [
                    { label: "低", value: 0 },
                    { label: "中", value: 1 },
                    { label: "高", value: 2 },
                    { label: "超高", value: 3 },
                ],
            },
            {
                key: "r.ViewDistanceScale",
                label: "视距缩放",
                description: "覆盖视距设置",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "r.DefaultFeature.Bloom",
                label: "泛光",
                description: "启用/禁用泛光效果",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.DefaultFeature.AmbientOcclusion",
                label: "环境光遮蔽",
                description: "启用/禁用环境光遮蔽",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.DefaultFeature.MotionBlur",
                label: "运动模糊",
                description: "启用/禁用运动模糊",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.Tonemapper.Quality",
                label: "色调映射质量",
                description: "色调映射质量设置",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.LightShaftQuality",
                label: "光束质量",
                description: "光束效果质量",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.Filter.SizeScale",
                label: "滤镜大小缩放",
                description: "滤镜大小缩放",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0.6,
            },
            {
                key: "r.Tonemapper.GrainQuantization",
                label: "色调映射颗粒量化",
                description: "色调映射颗粒量化",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.MaxAnisotropy",
                label: "最大各向异性",
                description: "最大各向异性过滤",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.TranslucencyVolumeBlur",
                label: "半透明体积模糊",
                description: "半透明体积模糊",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.MaterialQualityLevel",
                label: "材质质量级别",
                description: "材质质量级别",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.SSS.Scale",
                label: "次表面散射缩放",
                description: "次表面散射缩放",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.SSS.SampleSet",
                label: "次表面散射采样集",
                description: "次表面散射采样集",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "foliage.DiscardDataOnLoad",
                label: "植被加载时丢弃数据",
                description: "植被加载时丢弃数据",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "foliage.MaxTrianglesToRender",
                label: "植被最大渲染三角形",
                description: "植被最大渲染三角形数",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "r.Shadow.MaxCSMResolution",
                label: "阴影最大级联阴影贴图分辨率",
                description: "阴影最大级联阴影贴图分辨率",
                type: "number",
                section: "SystemSettings",
                defaultValue: 256,
            },
            {
                key: "r.Shadow.CSM.MaxCascades",
                label: "阴影级联最大级数",
                description: "阴影级联最大级数",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "r.ParticleLightQuality",
                label: "粒子光照质量",
                description: "粒子光照质量",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.SkyLightingQuality",
                label: "天空光照质量",
                description: "天空光照质量",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.Streaming.PoolSize",
                label: "纹理池大小",
                description: "设置此值等于或低于专用显存（MB）",
                type: "number",
                section: "SystemSettings",
                defaultValue: 128,
            },
            {
                key: "r.Streaming.MaxTempMemoryAllowed",
                label: "流式传输最大临时内存",
                description: "流式传输最大临时内存",
                type: "number",
                section: "SystemSettings",
                defaultValue: 64,
            },
            {
                key: "fx.Niagara.QualityLevel",
                label: "Niagara 质量级别",
                description: "Niagara 粒子系统质量级别",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.MipMapLODBias",
                label: "纹理 LOD 偏移",
                description: "影响纹理质量",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "r.Streaming.MipBias",
                label: "流式传输 Mip 偏移",
                description: "流式传输 Mip 偏移",
                type: "number",
                section: "SystemSettings",
                defaultValue: 2,
            },
            {
                key: "r.Streaming.AmortizeCPUToGPUCopy",
                label: "流式传输 CPU 到 GPU 复制摊销",
                description: "流式传输 CPU 到 GPU 复制摊销",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "r.Streaming.MaxNumTexturesToStreamPerFrame",
                label: "每帧流式传输最大纹理数",
                description: "每帧流式传输最大纹理数",
                type: "number",
                section: "SystemSettings",
                defaultValue: 5,
            },
            {
                key: "r.Streaming.Boost",
                label: "流式传输提升",
                description: "流式传输提升",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "r.MaxQualityMode",
                label: "最大质量模式",
                description: "最大质量模式",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.ViewDistanceScale.ApplySecondaryScale",
                label: "视距缩放应用次级缩放",
                description: "视距缩放应用次级缩放",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "r.ViewDistanceScale.SecondaryScale",
                label: "视距缩放次级缩放",
                description: "视距缩放次级缩放",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0.5,
            },
            {
                key: "r.SkeletalMeshLODBias",
                label: "骨骼网格 LOD 偏移",
                description: "控制骨骼网格细节级别",
                type: "number",
                section: "SystemSettings",
                defaultValue: 2,
            },
            {
                key: "r.StaticMeshLODDistanceScale",
                label: "静态网格 LOD 距离缩放",
                description: "控制静态网格细节级别",
                type: "number",
                section: "SystemSettings",
                defaultValue: 3,
            },
            {
                key: "r.SkeletalMesh.MinLodQualityLevel",
                label: "骨骼网格最小 LOD 质量级别",
                description: "骨骼网格最小 LOD 质量级别",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.Streaming.LimitPoolSizeToVRAM",
                label: "流式传输限制池大小到显存",
                description: "流式传输限制池大小到显存",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "r.Streaming.UseFixedPoolSize",
                label: "流式传输使用固定池大小",
                description: "流式传输使用固定池大小",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "r.Streaming.HLODStrategy",
                label: "流式传输 HLOD 策略",
                description: "流式传输 HLOD 策略",
                type: "number",
                section: "SystemSettings",
                defaultValue: 2,
            },
            {
                key: "r.Streaming.PerTextureBiasViewBoostEnabled",
                label: "流式传输每纹理偏移视图提升启用",
                description: "流式传输每纹理偏移视图提升启用",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "r.SkeletalMesh.StreamLODsEnabled",
                label: "骨骼网格流式传输 LOD 启用",
                description: "骨骼网格流式传输 LOD 启用",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.DistanceFieldShadowing",
                label: "距离场阴影",
                description: "启用/禁用距离场阴影",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.DistanceFieldAO",
                label: "距离场环境光遮蔽",
                description: "启用/禁用距离场环境光遮蔽",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.DynamicGlobalIlluminationMethod",
                label: "动态全局照明方法",
                description: "动态全局照明方法",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.ReflectionMethod",
                label: "反射方法",
                description: "反射方法",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.GenerateMeshDistanceFields",
                label: "生成网格距离场",
                description: "生成网格距离场",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.RayTracing",
                label: "光线追踪",
                description: "启用/禁用光线追踪",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.Lumen.DiffuseIndirect.Allow",
                label: "Lumen 漫反射",
                description: "启用/禁用 Lumen 漫反射",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.Lumen.Reflections.Allow",
                label: "Lumen 反射",
                description: "启用/禁用 Lumen 反射",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.Lumen.ScreenProbeGather.Allow",
                label: "Lumen 屏幕探针收集",
                description: "启用/禁用 Lumen 屏幕探针收集",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.FinishCurrentFrame",
                label: "完成当前帧",
                description: "完成当前帧",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.BasePassForceOutputsVelocity",
                label: "基础通道强制输出速度",
                description: "基础通道强制输出速度",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.MotionBlurQuality",
                label: "运动模糊质量",
                description: "运动模糊质量",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.AmbientOcclusionLevels",
                label: "环境光遮蔽级别",
                description: "环境光遮蔽级别",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.GBufferFormat",
                label: "G 缓冲格式",
                description: "G 缓冲格式",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.VirtualTexture",
                label: "虚拟纹理",
                description: "虚拟纹理",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.LightFunctionQuality",
                label: "光照函数质量",
                description: "光照函数质量",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.ShadowQuality",
                label: "阴影质量",
                description: "覆盖游戏内阴影质量",
                type: "select",
                section: "SystemSettings",
                defaultValue: 0,
                options: [
                    { label: "关闭", value: 0 },
                    { label: "低", value: 1 },
                    { label: "中", value: 2 },
                    { label: "高", value: 3 },
                ],
            },
            {
                key: "r.Shadow.MaxResolution",
                label: "阴影最大分辨率",
                description: "阴影最大分辨率",
                type: "number",
                section: "SystemSettings",
                defaultValue: 16,
            },
            {
                key: "r.Shadow.RadiusThreshold",
                label: "阴影半径阈值",
                description: "阴影半径阈值",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0.03,
            },
            {
                key: "r.Shadow.DistanceScale",
                label: "阴影距离缩放",
                description: "阴影距离缩放",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0.1,
            },
            {
                key: "r.AllowLandscapeShadows",
                label: "允许地形阴影",
                description: "允许地形阴影",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.ContactShadows",
                label: "接触阴影",
                description: "启用/禁用接触阴影",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.VolumetricFog",
                label: "体积雾",
                description: "启用/禁用体积雾",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.Fog",
                label: "雾效",
                description: "启用/禁用雾效",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.LightShafts",
                label: "光束",
                description: "启用/禁用光束效果",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.BloomQuality",
                label: "泛光质量",
                description: "影响泛光质量",
                type: "select",
                section: "SystemSettings",
                defaultValue: 0,
                options: [
                    { label: "关闭", value: 0 },
                    { label: "低", value: 1 },
                    { label: "中", value: 2 },
                    { label: "高", value: 3 },
                ],
            },
            {
                key: "r.EyeAdaptationQuality",
                label: "眼睛适应质量",
                description: "眼睛适应质量",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.TonemapperQuality",
                label: "色调映射质量",
                description: "色调映射质量",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.AmbientOcclusionRadiusScale",
                label: "环境光遮蔽半径缩放",
                description: "环境光遮蔽半径缩放",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.LensFlareQuality",
                label: "镜头光晕质量",
                description: "镜头光晕质量",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.SceneColorFringeQuality",
                label: "场景色边质量",
                description: "场景色边质量",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.DepthOfFieldQuality",
                label: "景深质量",
                description: "景深质量",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.RenderTargetPoolMin",
                label: "渲染目标池最小",
                description: "渲染目标池最小",
                type: "number",
                section: "SystemSettings",
                defaultValue: 100,
            },
            {
                key: "r.Upscale.Quality",
                label: "放大质量",
                description: "放大质量",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.TemporalAA.Upsampling",
                label: "时间 AA 放大",
                description: "时间 AA 放大",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.PostProcessAAQuality",
                label: "抗锯齿",
                description: "覆盖抗锯齿/后处理 AA",
                type: "select",
                section: "SystemSettings",
                defaultValue: 0,
                options: [
                    { label: "关闭", value: 0 },
                    { label: "低", value: 1 },
                    { label: "中", value: 2 },
                    { label: "高", value: 3 },
                ],
            },
            {
                key: "r.ScreenPercentage",
                label: "渲染比例",
                description: "覆盖分辨率/UI 缩放（渲染比例）",
                type: "number",
                section: "SystemSettings",
                defaultValue: 50,
            },
            {
                key: "r.RefractionQuality",
                label: "折射质量",
                description: "折射质量",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.ReflectionEnvironment",
                label: "反射环境",
                description: "反射环境",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.SSR.Quality",
                label: "SSR 质量",
                description: "屏幕空间反射质量",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.SSR.Temporal",
                label: "SSR 时间",
                description: "SSR 时间",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.SSR.HalfResSceneColor",
                label: "SSR 半分辨率场景颜色",
                description: "SSR 半分辨率场景颜色",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "fx.MaxCPUParticlesPerEmitter",
                label: "每发射器最大 CPU 粒子数",
                description: "每发射器最大 CPU 粒子数",
                type: "number",
                section: "SystemSettings",
                defaultValue: 10,
            },
            {
                key: "r.EmitterSpawnRateScale",
                label: "发射器生成率缩放",
                description: "发射器生成率缩放",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0.1,
            },
            {
                key: "r.FastBlurThreshold",
                label: "快速模糊阈值",
                description: "快速模糊阈值",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.TranslucencyLightingVolumeDim",
                label: "半透明光照体积维度",
                description: "半透明光照体积维度",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "foliage.DensityScale",
                label: "植被密度",
                description: "控制植被密度",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "grass.DensityScale",
                label: "草地密度",
                description: "控制草地密度",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.LODDistanceFactor",
                label: "LOD 距离因子",
                description: "LOD 距离因子",
                type: "number",
                section: "SystemSettings",
                defaultValue: 3,
            },
            {
                key: "r.DetailMode",
                label: "细节模式",
                description: "细节模式",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.DefaultFeature.AutoExposure",
                label: "自动曝光",
                description: "自动曝光",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.DefaultFeature.LensFlare",
                label: "镜头光晕",
                description: "镜头光晕",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.DefaultFeature.LightUnits",
                label: "光照单位",
                description: "光照单位",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "r.HZBOcclusion",
                label: "HZB 遮挡",
                description: "HZB 遮挡",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.FastVRam.Tonemapping",
                label: "快速显存色调映射",
                description: "快速显存色调映射",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.FastVRam.Bloom",
                label: "快速显存泛光",
                description: "快速显存泛光",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.FastVRam.DistanceFieldAOHZB",
                label: "快速显存距离场 AO HZB",
                description: "快速显存距离场 AO HZB",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.SceneColorFormat",
                label: "场景颜色格式",
                description: "场景颜色格式",
                type: "number",
                section: "SystemSettings",
                defaultValue: 3,
            },
            {
                key: "r.SupportSkyAtmosphere",
                label: "支持天空大气",
                description: "支持天空大气",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.SupportLowQualityLightmaps",
                label: "支持低质量光照贴图",
                description: "支持低质量光照贴图",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "r.SupportPointLightWholeSceneShadows",
                label: "支持点光源全场景阴影",
                description: "支持点光源全场景阴影",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.SupportSkyLighting",
                label: "支持天空光照",
                description: "支持天空光照",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.SupportStationarySkylight",
                label: "支持静止天光",
                description: "支持静止天光",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.MobileHDR",
                label: "移动 HDR",
                description: "启用/禁用移动设备 HDR",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.bForceCPUUpdateBoundingBoxes",
                label: "强制 CPU 更新包围盒",
                description: "强制 CPU 更新包围盒",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "r.DisableLODFade",
                label: "禁用 LOD 淡出",
                description: "禁用 LOD 淡出",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "r.Tessellation",
                label: "曲面细分",
                description: "曲面细分",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.Occlusion.MaxPixelShaderDiffuseLuminance",
                label: "遮挡最大像素着色器漫反射亮度",
                description: "遮挡最大像素着色器漫反射亮度",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0.01,
            },
            {
                key: "r.ForceLOD",
                label: "强制 LOD",
                description: "强制使用特定细节级别",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "r.LightmapStreaming",
                label: "光照贴图流式传输",
                description: "光照贴图流式传输",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "r.LightmapStreaming.MaxRequestedMipBias",
                label: "光照贴图流式传输最大请求 Mip 偏移",
                description: "光照贴图流式传输最大请求 Mip 偏移",
                type: "number",
                section: "SystemSettings",
                defaultValue: 2,
            },
            {
                key: "r.GTS.Async",
                label: "GTS 异步",
                description: "GTS 异步",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "r.Streaming.FullyLoadUsedTextures",
                label: "流式传输完全加载使用的纹理",
                description: "流式传输完全加载使用的纹理",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.Streaming.DefragDynamicBounds",
                label: "流式传输动态边界碎片整理",
                description: "流式传输动态边界碎片整理",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.Streaming.UnloadDoneInManagerTick",
                label: "流式传输在管理器刻度中卸载完成",
                description: "流式传输在管理器刻度中卸载完成",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.Streaming.UseMipsFarAway",
                label: "流式传输使用远距离 Mips",
                description: "流式传输使用远距离 Mips",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "r.Streaming.FullyLoadLODs",
                label: "流式传输完全加载 LODs",
                description: "流式传输完全加载 LODs",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.Streaming.MaxEffectiveSize",
                label: "流式传输最大有效大小",
                description: "流式传输最大有效大小",
                type: "number",
                section: "SystemSettings",
                defaultValue: 100,
            },
            {
                key: "r.Streaming.HiddenPrimitiveScale",
                label: "流式传输隐藏图元缩放",
                description: "流式传输隐藏图元缩放",
                type: "number",
                section: "SystemSettings",
                defaultValue: 2,
            },
            {
                key: "r.CustomDepth",
                label: "自定义深度",
                description: "自定义深度",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.AllowGlobalClipPlane",
                label: "允许全局裁剪平面",
                description: "允许全局裁剪平面",
                type: "number",
                section: "SystemSettings",
                defaultValue: 0,
            },
            {
                key: "r.AllowCompaction",
                label: "允许压缩",
                description: "允许压缩",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "r.Streaming.MaxTextureSize",
                label: "最大纹理尺寸",
                description: "增加此值或注释掉以获得更高纹理质量",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1024,
            },
            {
                key: "r.ForceReleaseTextureImmediately",
                label: "强制立即释放纹理",
                description: "强制立即释放纹理",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "r.MSAACount",
                label: "MSAA 抗锯齿",
                description: "多重采样抗锯齿：1=关闭, 2=2x, 4=4x, 8=8x",
                type: "select",
                section: "SystemSettings",
                defaultValue: 1,
                options: [
                    { label: "关闭", value: 1 },
                    { label: "2x MSAA", value: 2 },
                    { label: "4x MSAA", value: 4 },
                    { label: "8x MSAA", value: 8 },
                ],
            },
            {
                key: "r.HLOD",
                label: "HLOD",
                description: "分层细节",
                type: "number",
                section: "SystemSettings",
                defaultValue: 1,
            },
            {
                key: "r.HLOD.VisibilityQueryLODOffset",
                label: "HLOD 可见性查询 LOD 偏移",
                description: "HLOD 可见性查询 LOD 偏移",
                type: "number",
                section: "SystemSettings",
                defaultValue: 2,
            },
        ],
    },
    {
        name: "rendererSettings",
        label: "渲染器设置",
        description: "渲染器相关的高级设置",
        options: [
            {
                key: "r.Mobile.DisableVertexFog",
                label: "禁用顶点雾",
                description: "在移动设备上禁用顶点雾",
                type: "boolean",
                section: "/Script/Engine.RendererSettings",
                defaultValue: true,
            },
            {
                key: "r.DefaultFeature.Bloom",
                label: "泛光",
                description: "默认泛光设置",
                type: "boolean",
                section: "/Script/Engine.RendererSettings",
                defaultValue: false,
            },
            {
                key: "r.DefaultFeature.AmbientOcclusion",
                label: "环境光遮蔽",
                description: "默认环境光遮蔽设置",
                type: "boolean",
                section: "/Script/Engine.RendererSettings",
                defaultValue: false,
            },
            {
                key: "r.DefaultFeature.AntiAliasing",
                label: "抗锯齿",
                description: "默认抗锯齿设置",
                type: "number",
                section: "/Script/Engine.RendererSettings",
                defaultValue: 0,
            },
            {
                key: "r.DefaultFeature.LensFlare",
                label: "镜头光晕",
                description: "默认镜头光晕设置",
                type: "boolean",
                section: "/Script/Engine.RendererSettings",
                defaultValue: false,
            },
            {
                key: "r.DefaultFeature.LightUnits",
                label: "光照单位",
                description: "默认光照单位设置",
                type: "number",
                section: "/Script/Engine.RendererSettings",
                defaultValue: 1,
            },
            {
                key: "r.MobileHDR",
                label: "移动 HDR",
                description: "启用/禁用移动设备 HDR",
                type: "boolean",
                section: "/Script/Engine.RendererSettings",
                defaultValue: false,
            },
            {
                key: "r.AllowOcclusionQueries",
                label: "允许遮挡查询",
                description: "允许遮挡查询",
                type: "number",
                section: "/Script/Engine.RendererSettings",
                defaultValue: true,
            },
            {
                key: "r.SupportLowQualityLightmaps",
                label: "低质量光照贴图",
                description: "支持低质量光照贴图",
                type: "number",
                section: "/Script/Engine.RendererSettings",
                defaultValue: true,
            },
            {
                key: "r.SupportStationarySkylight",
                label: "静止天光",
                description: "支持静止天光",
                type: "boolean",
                section: "/Script/Engine.RendererSettings",
                defaultValue: false,
            },
            {
                key: "r.SupportSkyLighting",
                label: "天空光照",
                description: "支持天空光照",
                type: "boolean",
                section: "/Script/Engine.RendererSettings",
                defaultValue: false,
            },
            {
                key: "r.SupportPointLightWholeSceneShadows",
                label: "点光源全场景阴影",
                description: "支持点光源全场景阴影",
                type: "boolean",
                section: "/Script/Engine.RendererSettings",
                defaultValue: false,
            },
            {
                key: "r.Shadow.CSM.MaxCascades",
                label: "阴影级联最大级数",
                description: "阴影级联最大级数",
                type: "number",
                section: "/Script/Engine.RendererSettings",
                defaultValue: 1,
            },
            {
                key: "r.ReflectionEnvironment",
                label: "反射环境",
                description: "反射环境",
                type: "boolean",
                section: "/Script/Engine.RendererSettings",
                defaultValue: false,
            },
            {
                key: "r.ReflectionCaptureResolution",
                label: "反射捕获分辨率",
                description: "反射捕获分辨率",
                type: "number",
                section: "/Script/Engine.RendererSettings",
                defaultValue: 16,
            },
            {
                key: "r.TranslucentSortPolicy",
                label: "半透明排序策略",
                description: "半透明排序策略",
                type: "number",
                section: "/Script/Engine.RendererSettings",
                defaultValue: 0,
            },
            {
                key: "r.DistanceFieldAO",
                label: "距离场环境光遮蔽",
                description: "启用/禁用距离场环境光遮蔽",
                type: "number",
                section: "/Script/Engine.RendererSettings",
                defaultValue: 0,
            },
            {
                key: "r.DistanceFieldShadowing",
                label: "距离场阴影",
                description: "启用/禁用距离场阴影",
                type: "boolean",
                section: "/Script/Engine.RendererSettings",
                defaultValue: false,
            },
            {
                key: "r.RayTracing",
                label: "光线追踪",
                description: "启用/禁用光线追踪",
                type: "boolean",
                section: "/Script/Engine.RendererSettings",
                defaultValue: false,
            },
        ],
    },
    {
        name: "consoleVariables",
        label: "控制台变量",
        description: "控制台变量设置",
        options: [
            {
                key: "r.Streaming.MaxDynamicPoolSize",
                label: "流式传输最大动态池大小",
                description: "流式传输最大动态池大小",
                type: "number",
                section: "ConsoleVariables",
                defaultValue: 100,
            },
            {
                key: "r.Streaming.FramesForFullUpdate",
                label: "流式传输完全更新帧数",
                description: "流式传输完全更新帧数",
                type: "number",
                section: "ConsoleVariables",
                defaultValue: 15,
            },
            {
                key: "r.UseShaderCaching",
                label: "使用着色器缓存",
                description: "使用着色器缓存",
                type: "number",
                section: "ConsoleVariables",
                defaultValue: 1,
            },
            {
                key: "r.UseAsyncPrecompile",
                label: "使用异步预编译",
                description: "使用异步预编译",
                type: "number",
                section: "ConsoleVariables",
                defaultValue: 1,
            },
            {
                key: "r.UseAsyncPrecompileForFeatureLevelUpgrade",
                label: "使用特性级别升级异步预编译",
                description: "使用特性级别升级异步预编译",
                type: "number",
                section: "ConsoleVariables",
                defaultValue: 1,
            },
            {
                key: "r.TargetPrecompileFrameTime",
                label: "目标预编译帧时间",
                description: "目标预编译帧时间",
                type: "number",
                section: "ConsoleVariables",
                defaultValue: 10,
            },
            {
                key: "r.PrecompileShadersForFeatureLevel",
                label: "为特性级别预编译着色器",
                description: "为特性级别预编译着色器",
                type: "number",
                section: "ConsoleVariables",
                defaultValue: 1,
            },
            {
                key: "r.GPUCulling",
                label: "GPU 剔除",
                description: "GPU 剔除",
                type: "number",
                section: "ConsoleVariables",
                defaultValue: 0,
            },
            {
                key: "r.EarlyZPass",
                label: "早期 Z 通道",
                description: "早期 Z 通道",
                type: "number",
                section: "ConsoleVariables",
                defaultValue: 2,
            },
            {
                key: "r.ParallelSceneRendering",
                label: "并行场景渲染",
                description: "并行场景渲染",
                type: "number",
                section: "ConsoleVariables",
                defaultValue: 1,
            },
            {
                key: "fx.ParallelSystemEvaluation",
                label: "并行系统评估",
                description: "并行系统评估",
                type: "number",
                section: "ConsoleVariables",
                defaultValue: 1,
            },
            {
                key: "fx.MaxGPUParticlesSpawnCount",
                label: "最大 GPU 粒子生成数",
                description: "最大 GPU 粒子生成数",
                type: "number",
                section: "ConsoleVariables",
                defaultValue: 512,
            },
            {
                key: "r.DoParallelDepthPrepass",
                label: "并行深度预通道",
                description: "并行深度预通道",
                type: "number",
                section: "ConsoleVariables",
                defaultValue: 1,
            },
        ],
    },
]

// 需要保留的默认段（不进行编辑）
export const preservedSections = ["Core.System", "WindowsApplication.Accessibility"]
