/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioPlayButton: typeof import('./components/AudioPlayButton.vue')['default']
    CheckAnimationButton: typeof import('./components/CheckAnimationButton.vue')['default']
    ContextMenu: typeof import('./components/contextmenu/ContextMenu.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    DialogClose: typeof import('radix-vue')['DialogClose']
    DialogContent: typeof import('radix-vue')['DialogContent']
    DialogDescription: typeof import('radix-vue')['DialogDescription']
    DialogOverlay: typeof import('radix-vue')['DialogOverlay']
    DialogPortal: typeof import('radix-vue')['DialogPortal']
    DialogRoot: typeof import('radix-vue')['DialogRoot']
    DialogTitle: typeof import('radix-vue')['DialogTitle']
    DialogTrigger: typeof import('radix-vue')['DialogTrigger']
    EmojiSelect: typeof import('./components/EmojiSelect.vue')['default']
    GQAutoPage: typeof import('./components/GQAutoPage.vue')['default']
    GQQuery: typeof import('./components/GQQuery.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    LocalQQ: typeof import('./components/LocalQQ.vue')['default']
    Popover: typeof import('./components/Popover.vue')['default']
    QQAvatar: typeof import('./components/QQAvatar.vue')['default']
    ResizeableWindow: typeof import('./components/ResizeableWindow.vue')['default']
    RichInput: typeof import('./components/RichInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollArea: typeof import('./components/ScrollArea.vue')['default']
    ScrollAreaRoot: typeof import('radix-vue')['ScrollAreaRoot']
    ScrollAreaScrollbar: typeof import('radix-vue')['ScrollAreaScrollbar']
    ScrollAreaThumb: typeof import('radix-vue')['ScrollAreaThumb']
    ScrollAreaViewport: typeof import('radix-vue')['ScrollAreaViewport']
    Select: typeof import('./components/select/Select.vue')['default']
    SelectItem: typeof import('./components/select/SelectItem.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SidebarButton: typeof import('./components/SidebarButton.vue')['default']
    StatisticsProgress: typeof import('./components/StatisticsProgress.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    Tooltip: typeof import('./components/Tooltip.vue')['default']
    UserItem: typeof import('./components/UserItem.vue')['default']
  }
}

// For TSX support
declare global {
  const AudioPlayButton: typeof import('./components/AudioPlayButton.vue')['default']
  const CheckAnimationButton: typeof import('./components/CheckAnimationButton.vue')['default']
  const ContextMenu: typeof import('./components/contextmenu/ContextMenu.vue')['default']
  const Counter: typeof import('./components/Counter.vue')['default']
  const Dialog: typeof import('./components/Dialog.vue')['default']
  const DialogClose: typeof import('radix-vue')['DialogClose']
  const DialogContent: typeof import('radix-vue')['DialogContent']
  const DialogDescription: typeof import('radix-vue')['DialogDescription']
  const DialogOverlay: typeof import('radix-vue')['DialogOverlay']
  const DialogPortal: typeof import('radix-vue')['DialogPortal']
  const DialogRoot: typeof import('radix-vue')['DialogRoot']
  const DialogTitle: typeof import('radix-vue')['DialogTitle']
  const DialogTrigger: typeof import('radix-vue')['DialogTrigger']
  const EmojiSelect: typeof import('./components/EmojiSelect.vue')['default']
  const GQAutoPage: typeof import('./components/GQAutoPage.vue')['default']
  const GQQuery: typeof import('./components/GQQuery.vue')['default']
  const Icon: typeof import('./components/Icon.vue')['default']
  const LocalQQ: typeof import('./components/LocalQQ.vue')['default']
  const Popover: typeof import('./components/Popover.vue')['default']
  const QQAvatar: typeof import('./components/QQAvatar.vue')['default']
  const ResizeableWindow: typeof import('./components/ResizeableWindow.vue')['default']
  const RichInput: typeof import('./components/RichInput.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const ScrollArea: typeof import('./components/ScrollArea.vue')['default']
  const ScrollAreaRoot: typeof import('radix-vue')['ScrollAreaRoot']
  const ScrollAreaScrollbar: typeof import('radix-vue')['ScrollAreaScrollbar']
  const ScrollAreaThumb: typeof import('radix-vue')['ScrollAreaThumb']
  const ScrollAreaViewport: typeof import('radix-vue')['ScrollAreaViewport']
  const Select: typeof import('./components/select/Select.vue')['default']
  const SelectItem: typeof import('./components/select/SelectItem.vue')['default']
  const Sidebar: typeof import('./components/Sidebar.vue')['default']
  const SidebarButton: typeof import('./components/SidebarButton.vue')['default']
  const StatisticsProgress: typeof import('./components/StatisticsProgress.vue')['default']
  const Toast: typeof import('./components/Toast.vue')['default']
  const Tooltip: typeof import('./components/Tooltip.vue')['default']
  const UserItem: typeof import('./components/UserItem.vue')['default']
}